apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeswarm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeswarm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kubeswarm.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: {{ .Values.service.port }}
      targetPort: webhook
      protocol: TCP
    - name: mcp-gateway
      port: 8093
      targetPort: mcp-gateway
      protocol: TCP
    {{- if .Values.admissionWebhooks.enabled }}
    - name: admission
      port: 9443
      targetPort: admission
      protocol: TCP
    {{- end }}
